cube_coords:           [[-7, 7], [-7, 7], [-9, 9]]
num_elem_init:            [15, 15, 17]
mesh_adaptation:            true

# atomic coordinates below are written in terms of the silicon lattice constant
#atomic_coords:      [[[0.0, 0.0, -0.5], [0.0, 0.0, 0.5]],
#                     [[0.0, 0.0, -1.0], [0.0, 0.0, 1.0]],
#                     [[0.0, 0.0, -1.5], [0.0, 0.0, 1.5]],
#                     [[0.0, 0.0, -2.0], [0.0, 0.0, 2.0]],
#                     [[0.0, 0.0, -2.5], [0.0, 0.0, 2.5]],
#                     [[0.0, 0.0, -3.0], [0.0, 0.0, 3.0]],
#                     [[0.0, 0.0, -3.5], [0.0, 0.0, 3.5]],
#                     [[0.0, 0.0, -4.0], [0.0, 0.0, 4.0]],
#                     [[0.0, 0.0, -4.5], [0.0, 0.0, 4.5]],
#                     [[0.0, 0.0, -5.0], [0.0, 0.0, 5.0]],
#                     [[0.0, 0.0, -5.5], [0.0, 0.0, 5.5]],
#                     [[0.0, 0.0, -6.0], [0.0, 0.0, 6.0]],
#                     [[0.0, 0.0, -6.5], [0.0, 0.0, 6.5]],
#                     [[0.0, 0.0, -7.0], [0.0, 0.0, 7.0]],
#                     [[0.0, 0.0, -7.5], [0.0, 0.0, 7.5]],
#                     [[0.0, 0.0, -8.0], [0.0, 0.0, 8.0]],
#                     [[0.0, 0.0, -8.5], [0.0, 0.0, 8.5]],
#                     [[0.0, 0.0, -9.0], [0.0, 0.0, 9.0]],
#                     [[0.0, 0.0, -9.5], [0.0, 0.0, 9.5]],
#                     [[0.0, 0.0, -10.0], [0.0, 0.0, 10.0]],
#                     [[0.0, 0.0, -10.5], [0.0, 0.0, 10.5]],
#                     [[0.0, 0.0, -11.0], [0.0, 0.0, 11.0]]]

#atomic_coords:      [[[0.0, 0.0, -9.0], [0.0, 0.0, 9.0]],
#                     [[0.0, 0.0, -9.5], [0.0, 0.0, 9.5]]]

atomic_coords:      [[[0.0, 0.0, -5.0], [0.0, 0.0, 5.0]],
                     [[0.0, 0.0, -5.5], [0.0, 0.0, 5.5]],
                     [[0.0, 0.0, -11.0], [0.0, 0.0, 11.0]],
                     [[0.0, 0.0, -11.5], [0.0, 0.0, 11.5]],
                     [[0.0, 0.0, -12.0], [0.0, 0.0, 12.0]],
                     [[0.0, 0.0, -12.5], [0.0, 0.0, 12.5]]]

field:               [0.0, 0.0, 0.0]

